apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_USER: bXlzcWw=              # mysql
  MYSQL_PASSWORD: bXlzcWw=          # mysql
  MYSQL_DATABASE: dGVzdGRi          # testdb
  MYSQL_ROOT_PASSWORD: dmVyeXNlY3VyZQ==  # verysecure

### optional for this Project But in real production using secrets for Database is best practice ###
